name: qt5-core22
base: core22 
version: '22.04.1'
summary: Qt5 runtime for core22
description: |
  This snap is to be consumed by various Qt apps which uses Qt 5 packages provided from 
  Ubuntu official repository.
  Qt provides C++ classes and QML types for rendering GUI.

grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: [amd64]
    build-for: [amd64]
    
slots: 
  qt5-core22:
    interface: content
    read: 
      - /

parts:
  qt5:
    plugin: nil
    stage-packages:
      # Platform
      #- adwaita-icon-theme
      #- dmz-cursor-theme
      - fontconfig
      - freeglut3
      #- gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libglib2.0-bin
      - libglu1-mesa
      - libice6
      - libxkbcommon0
      #- light-themes
      - locales-all
      - shared-mime-info
      - fonts-ubuntu
      - xdg-user-dirs

      # Other Desktop integration
      - ibus-gtk3
      - libibus-1.0-5
      - libcanberra-gtk3-module
      - qt5-gtk-platformtheme
      - qt5-xdgdesktopportal-platformtheme
      - gsettings-desktop-schemas

      # Qt modules from core20
      - libqt5gui5
      - libqt5svg5
      - libqt5waylandclient5
      - libqt5webkit5
      - libqt5x11extras5
            
  cleanup:
    after:
      - qt5
    plugin: nil
    override-prime: |
      set -eux
      
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      
      find $CRAFT_PRIME/usr/share -type d -empty -delete
